# 默认每天6:30执行，cron使用格林威治标准时间，时差8小时

name: Start

on:
   push:
   gollum:
   schedule:
       - cron: '15 16,5 * * *' #在北京时间00:00和12:00运行

jobs:
  TiebaSignIn:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        BDUSS: ${{ secrets.BDUSS }}
        PUSHINFO: ${{ secrets.PUSHINFO }}
      run: |
        mvn compile exec:java -Dexec.mainClass="top.srcrs.Run" -Dexec.args="${BDUSS} ${PUSHINFO}"
